"""Controlled chapter taxonomy for M. Laxmikanth, Indian Polity, 8th Edition.

Source: McGraw Hill official English 8th-edition table of contents.
Chapter numbers are stable classification identifiers.
"""

LAXMIKANTH_8TH_EDITION = {
    1: 'Historical Background',
    2: 'Making of the Constitution',
    3: 'Concept of Constitution',
    4: 'Salient Features of the Constitution',
    5: 'Preamble of the Constitution',
    6: 'Union and its Territory',
    7: 'Citizenship',
    8: 'Fundamental Rights',
    9: 'Directive Principles of State Policy',
    10: 'Fundamental Duties',
    11: 'Amendment of the Constitution',
    12: 'Basic Structure of the Constitution',
    13: 'Parliamentary System',
    14: 'Federal System',
    15: 'Centre–State Relations',
    16: 'Inter-State Relations',
    17: 'Emergency Provisions',
    18: 'President',
    19: 'Vice-President',
    20: 'Prime Minister',
    21: 'Central Council of Ministers',
    22: 'Cabinet Committees',
    23: 'Parliament',
    24: 'Parliamentary Committees',
    25: 'Parliamentary Group',
    26: 'Supreme Court',
    27: 'Judicial Review',
    28: 'Judicial Activism',
    29: 'Public Interest Litigation',
    30: 'Governor',
    31: 'Chief Minister',
    32: 'State Council of Ministers',
    33: 'State Legislature',
    34: 'High Court',
    35: 'Subordinate Courts',
    36: 'Tribunals',
    37: 'National Consumer Disputes Redressal Commission',
    38: 'Lok Adalat and other courts',
    39: 'Panchayati Raj',
    40: 'Municipalities',
    41: 'Union Territories',
    42: 'Scheduled and Tribal Areas',
    43: 'Election Commission',
    44: 'Union Public Service Commission',
    45: 'State Public Service Commission',
    46: 'Finance Commission',
    47: 'Goods and Services Tax Council',
    48: 'National Commission for SCs',
    49: 'National Commission for STs',
    50: 'National Commission for BCs',
    51: 'Special Officer for Linguistic Minorities',
    52: 'Comptroller and Auditor General of India',
    53: 'Attorney General of India',
    54: 'Advocate General of the State',
    55: 'Constitutional Prescriptions',
    56: 'NITI Aayog',
    57: 'National Human Rights Commission',
    58: 'State Human Rights Commission',
    59: 'National Commission for Women',
    60: 'National Commission for Protection of Child Rights',
    61: 'National Commission for Minorities',
    62: 'Central Information Commission',
    63: 'State Information Commission',
    64: 'Central Vigilance Commission',
    65: 'Central Bureau of Investigation',
    66: 'Lokpal and Lokayuktas',
    67: 'National Investigation Agency',
    68: 'National Disaster Management Authority',
    69: 'Bar Council of India',
    70: 'Law Commission of India',
    71: 'Delimitation Commission of India',
    72: 'Co-operative Societies',
    73: 'Official Language',
    74: 'Public Services',
    75: 'Rights and Liabilities of the Government',
    76: 'Special Provisions Relating to Certain Classes',
    77: 'Special Provisions for Some States',
    78: 'Political Parties',
    79: 'Role of Regional Parties',
    80: 'Elections',
    81: 'Election Laws',
    82: 'Electoral Reforms',
    83: 'Voting Behaviour',
    84: 'Coalition Government',
    85: 'Anti-Defection Law',
    86: 'Pressure Groups',
    87: 'National Integration',
    88: 'Foreign Policy',
    89: 'National Commission to Review the Working of the Constitution',
    90: 'Landmark Judgements and their Impact',
    91: 'Important Doctrines of Constitutional Interpretation',
    92: 'World Constitutions',
}

CHAPTER_BY_TITLE = {
    'Historical Background': 1,
    'Making of the Constitution': 2,
    'Concept of Constitution': 3,
    'Salient Features of the Constitution': 4,
    'Preamble of the Constitution': 5,
    'Union and its Territory': 6,
    'Citizenship': 7,
    'Fundamental Rights': 8,
    'Directive Principles of State Policy': 9,
    'Fundamental Duties': 10,
    'Amendment of the Constitution': 11,
    'Basic Structure of the Constitution': 12,
    'Parliamentary System': 13,
    'Federal System': 14,
    'Centre–State Relations': 15,
    'Inter-State Relations': 16,
    'Emergency Provisions': 17,
    'President': 18,
    'Vice-President': 19,
    'Prime Minister': 20,
    'Central Council of Ministers': 21,
    'Cabinet Committees': 22,
    'Parliament': 23,
    'Parliamentary Committees': 24,
    'Parliamentary Group': 25,
    'Supreme Court': 26,
    'Judicial Review': 27,
    'Judicial Activism': 28,
    'Public Interest Litigation': 29,
    'Governor': 30,
    'Chief Minister': 31,
    'State Council of Ministers': 32,
    'State Legislature': 33,
    'High Court': 34,
    'Subordinate Courts': 35,
    'Tribunals': 36,
    'National Consumer Disputes Redressal Commission': 37,
    'Lok Adalat and other courts': 38,
    'Panchayati Raj': 39,
    'Municipalities': 40,
    'Union Territories': 41,
    'Scheduled and Tribal Areas': 42,
    'Election Commission': 43,
    'Union Public Service Commission': 44,
    'State Public Service Commission': 45,
    'Finance Commission': 46,
    'Goods and Services Tax Council': 47,
    'National Commission for SCs': 48,
    'National Commission for STs': 49,
    'National Commission for BCs': 50,
    'Special Officer for Linguistic Minorities': 51,
    'Comptroller and Auditor General of India': 52,
    'Attorney General of India': 53,
    'Advocate General of the State': 54,
    'Constitutional Prescriptions': 55,
    'NITI Aayog': 56,
    'National Human Rights Commission': 57,
    'State Human Rights Commission': 58,
    'National Commission for Women': 59,
    'National Commission for Protection of Child Rights': 60,
    'National Commission for Minorities': 61,
    'Central Information Commission': 62,
    'State Information Commission': 63,
    'Central Vigilance Commission': 64,
    'Central Bureau of Investigation': 65,
    'Lokpal and Lokayuktas': 66,
    'National Investigation Agency': 67,
    'National Disaster Management Authority': 68,
    'Bar Council of India': 69,
    'Law Commission of India': 70,
    'Delimitation Commission of India': 71,
    'Co-operative Societies': 72,
    'Official Language': 73,
    'Public Services': 74,
    'Rights and Liabilities of the Government': 75,
    'Special Provisions Relating to Certain Classes': 76,
    'Special Provisions for Some States': 77,
    'Political Parties': 78,
    'Role of Regional Parties': 79,
    'Elections': 80,
    'Election Laws': 81,
    'Electoral Reforms': 82,
    'Voting Behaviour': 83,
    'Coalition Government': 84,
    'Anti-Defection Law': 85,
    'Pressure Groups': 86,
    'National Integration': 87,
    'Foreign Policy': 88,
    'National Commission to Review the Working of the Constitution': 89,
    'Landmark Judgements and their Impact': 90,
    'Important Doctrines of Constitutional Interpretation': 91,
    'World Constitutions': 92,
}

CHAPTER_NUMBERS = tuple(LAXMIKANTH_8TH_EDITION)


def get_chapter_title(chapter_number: int) -> str:
    return LAXMIKANTH_8TH_EDITION[chapter_number]


def is_valid_chapter(chapter_number: int) -> bool:
    return chapter_number in LAXMIKANTH_8TH_EDITION
