"""add document chunks table with pgvector

Revision ID: 3d1f836cf331
Revises: 67e13f8ba8be
Create Date: 2026-09-23 03:57:54.672401

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1f836cf331'
down_revision: Union[str, Sequence[str], None] = '67e13f8ba8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prid', sa.String(length=100), nullable=False),
    sa.Column('chapter_name', sa.String(length=250), nullable=False),
    sa.Column('topic', sa.String(length=250), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=4096), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
