"""add user_chapter_progress table

Revision ID: 77f2b22eac5c
Revises: 5235eb94f865
Create Date: 2026-09-25 16:13:00.924798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f2b22eac5c'
down_revision: Union[str, Sequence[str], None] = '5235eb94f865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(length=255), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_chapter_progress_id'), 'user_chapter_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_chapter_progress_user_id'), 'user_chapter_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chapter_progress_user_id'), table_name='user_chapter_progress')
    op.drop_index(op.f('ix_user_chapter_progress_id'), table_name='user_chapter_progress')
    op.drop_table('user_chapter_progress')
    # ### end Alembic commands ###
