"""add_issue_dossiers_and_edge_cases

Revision ID: cf5db8aa7cba
Revises: f8b643596668
Create Date: 2026-10-05 14:18:10.524193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf5db8aa7cba'
down_revision: Union[str, Sequence[str], None] = 'f8b643596668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_dossiers',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('issue_slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('canonical_summary', sa.Text(), nullable=True),
    sa.Column('mains_framework', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_issue_dossiers_chapter_name'), 'issue_dossiers', ['chapter_name'], unique=False)
    op.create_index(op.f('ix_issue_dossiers_issue_slug'), 'issue_dossiers', ['issue_slug'], unique=True)
    op.create_table('issue_graph_edges',
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('issue_slug', sa.String(length=120), nullable=False),
    sa.Column('prid', sa.String(length=100), nullable=False),
    sa.Column('publication', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('perspective_stance', sa.String(length=64), nullable=False),
    sa.Column('core_claim', sa.Text(), nullable=False),
    sa.Column('legal_anchors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_slug'], ['issue_dossiers.issue_slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_issue_graph_edges_event_date'), 'issue_graph_edges', ['event_date'], unique=False)
    op.create_index(op.f('ix_issue_graph_edges_issue_slug'), 'issue_graph_edges', ['issue_slug'], unique=False)
    op.create_index(op.f('ix_issue_graph_edges_prid'), 'issue_graph_edges', ['prid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_graph_edges_prid'), table_name='issue_graph_edges')
    op.drop_index(op.f('ix_issue_graph_edges_issue_slug'), table_name='issue_graph_edges')
    op.drop_index(op.f('ix_issue_graph_edges_event_date'), table_name='issue_graph_edges')
    op.drop_table('issue_graph_edges')
    op.drop_index(op.f('ix_issue_dossiers_issue_slug'), table_name='issue_dossiers')
    op.drop_index(op.f('ix_issue_dossiers_chapter_name'), table_name='issue_dossiers')
    op.drop_table('issue_dossiers')
    # ### end Alembic commands ###
